CREATE DATABASE HOMEFARM;
USE HOMEFARM;

-- -----------------------------------------------------
-- Table `Usuário`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USUARIO` (
  `ID` INT NOT NULL,
  `NOME` VARCHAR(70) NOT NULL,
  `SOBRENOME` VARCHAR(70) NULL,
  `LOGIN` VARCHAR(45) NOT NULL,
  `SENHA` VARCHAR(45) NOT NULL,
  `ADMINISTRADOR` TINYINT NOT NULL,
  `DATAULTIMOACESSO` DATETIME NULL,
  PRIMARY KEY (`ID`));

INSERT INTO USUARIO VALUES (1, "WILLIAM", "KOLOSQUE", "WILLIAMKOLOSQUE", "123456", 1, "23-05-2017");

-- -----------------------------------------------------
-- Table `Vaca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `VACA` (
  `ID` INT  NULL,
  `LACTACAO` DATETIME NULL,
  `PRODUCAO` DOUBLE NULL,
  `FILHOS` INT NULL,
  PRIMARY KEY (`ID`));

INSERT INTO VACA VALUES (1, "23-04-2017", 23.4, 3);
-- -----------------------------------------------------
-- Table `Cavalo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CAVALO` (
  `ID` INT  NULL,
  `PO` TINYINT NULL,
  `FILHOS` INT NULL,
  PRIMARY KEY (`ID`));

INSERT INTO CAVALO VALUES (1, 1, 3);
-- -----------------------------------------------------
-- Table `Ovelha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OVELHA` (
  `ID` INT  NULL,
  `PO` TINYINT NULL,
  `PRODUCAO` DOUBLE NULL,
  PRIMARY KEY (`ID`));

INSERT INTO OVELHA VALUES (1, 1, 3.5);
-- -----------------------------------------------------
-- Table `Porco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PORCO` (
  `ID` INT  NULL,
  `PRODUCAO` DOUBLE NULL,
  `FILHOS` INT NULL,
  PRIMARY KEY (`ID`));

INSERT INTO PORCO VALUES (1, 12.4, 12);


-- -----------------------------------------------------
-- Table `Raca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RACA` (
  `ID` INT NOT NULL,
  `ORIGEM` VARCHAR(45) NULL,
  `NOMERACA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`));

INSERT INTO RACA VALUES (1, "HOLANDA", "HOLANDES");

-- -----------------------------------------------------
-- Table `Animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ANIMAL` (
  `ID` INT NOT NULL,
  `CODIGOBRINCO` INT NOT NULL,
  `NOME` VARCHAR(85) NOT NULL,
  `DATA_NACIMENTO` DATE NULL,
  `NOME_PAI` VARCHAR(85) NULL,
  `NOME_MAE` VARCHAR(85) NULL,
  `SEXO` VARCHAR(45) NOT NULL,
  `PESO` DOUBLE NULL,
  `MORTO` TINYINT NULL,
  `VENDIDA` TINYINT NULL,
  `RACA_Id` INT NOT NULL,
  `VACA_ID` INT NULL,
  `CAVALO_ID` INT NULL,
  `OVELHA_ID` INT NULL,
  `PORCO_ID` INT NULL,
  
  PRIMARY KEY (`ID`),

    INDEX `FK_ANIMAL_RACA1_IDX` (`RACA_ID` ASC),
      INDEX `FK_ANIMAL_VACA1_IDX` (`Vaca_ID` ASC),
  INDEX `FK_ANIMAL_CAVALO1_IDX` (`CAVALO_ID` ASC),
  INDEX `FK_ANIMAL_OVELHA1_IDX` (`OVELHA_ID` ASC),
  INDEX `FK_ANIMAL_PORCO1_IDX` (`PORCO_ID` ASC),
  
  


      CONSTRAINT `FK_ANIMAL_RACA1_IDX`
    FOREIGN KEY (`RACA_ID`)
    REFERENCES `RACA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ANIMAL_VACA1`
    FOREIGN KEY (`VACA_ID`)
    REFERENCES `VACA` (`ID`)
  ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ANIMAL_CAVALO`
    FOREIGN KEY (`CAVALO_ID`)
    REFERENCES `CAVALO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ANIMAL_OVELHA1`
    FOREIGN KEY (`OVELHA_ID`)
    REFERENCES `OVELHA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ANIMAL_PORCO1`
    FOREIGN KEY (`PORCO_ID`)
    REFERENCES `PORCO` (`ID`)
      ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO ANIMAL VALUES (1, 12, "ESPOLETA", "21-03-2013", "TROVAO AZUL", "TANDARA", "FEMININO", 32.5, 2, 2, 1,1,NULL,NULL,NULL);
-- -----------------------------------------------------
-- Table `Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MEDICAMENTO` (
  `ID` INT NOT NULL,
  `NOME` VARCHAR(85) NOT NULL,
  `DESCRICAO` TEXT(200) NULL,
  `DATAVALIDADE` DATE NOT NULL,
  `ESTOCADO` INT NOT NULL,
  PRIMARY KEY (`ID`));

INSERT INTO MEDICAMENTO VALUES (1, "TERRAMISINA", "MEDICAMENTO UTILIZADOS PARA VARIOS ANIMAIS E FRAQUESAS", "21-12-2021", 4);
-- -----------------------------------------------------
-- Table `Racao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RACAO` (
  `ID` INT NOT NULL,
  `NOME` VARCHAR(45) NULL,
  `TIPO` VARCHAR(45) NULL,
  `DATAVALIDADE` DATE NULL,
  `QUANTIDADE` INT NULL,
  `DESCRICAO` TEXT(200) NULL,
  PRIMARY KEY (`ID`));

INSERT INTO RACAO VALUES (1, "FARELO DE ARROZ", "PARA VACAS", "21-05-2019",15, "FARELO DERIVADO DO ARROZ, BOM PARA DIVERSOS ANIMAIS");

-- -----------------------------------------------------
-- Table `Propriedade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PROPRIEDADE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CEP` VARCHAR(45) NULL,
  `LOGRADOURO` VARCHAR(255) NULL,
  `NUMERO` VARCHAR(45) NULL,
  `COMPLEMENTO` VARCHAR(255) NULL,
  `BAIRRO` VARCHAR(255) NULL,
  `CIDADE` VARCHAR(85) NULL,
  `ESTADO` VARCHAR(45) NULL,
  `USUARIO_ID` INT NULL,
  `ANIMAL_ID` INT NULL,
  `MEDICAMENTO_ID` INT NULL,
  `RACAO_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_PROPRIEDADE_USUARIO1_IDX` (`USUARIO_ID` ASC),
  INDEX `FK_PROPRIEDADE_ANIMAL1_IDX` (`ANIMAL_ID` ASC),
  INDEX `FK_PROPRIEDADE_MEDICAMENTO1_IDX` (`MEDICAMENTO_ID` ASC),
  INDEX `FK_PROPRIEDADE_RACAO1_IDX` (`RACAO_ID` ASC),
  CONSTRAINT `FK_PROPRIEDADE_USUARIO`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROPRIEDADE_ANIMAL1`
    FOREIGN KEY (`ANIMAL_ID`)
    REFERENCES `ANIMAL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROPRIEDADE_MEDICAMENTO1`
    FOREIGN KEY (`MEDICAMENTO_ID`)
    REFERENCES `MEDICAMENTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PROPRIEDADE_RACAO1`
    FOREIGN KEY (`RACAO_ID`)
    REFERENCES `RACAO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO PROPRIEDADE VALUES(1,"962000000","RUA DAS ACACIAS","1255","RUA","2 DISTRITO","CAPAO DO LEAO","RS",1,1,1,1);
-- -----------------------------------------------------
-- Table `Aplicacao_Medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `APLICACAO_MEDICAMENTO` (
  `ID` INT NOT NULL,
  `DATAAPLICACAO` DATE NULL,
  `QUANTIDADE` INT NULL,
  `OBSERVACAO` TEXT(200) NULL,
  `USUARIO_ID` INT NOT NULL,
  `MEDICAMENTO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_APLICACAO_MEDICAMENTO_USUARIO1_IDX` (`USUARIO_ID` ASC),
  INDEX `fk_APLICACAO_MEDICAMENTO_MEDICAMENTO1_IDX` (`MEDICAMENTO_ID` ASC),
  CONSTRAINT `FK_APLICACAO_MEDICAMENTO_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `USUARIO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_APLICACAO_MEDICAMENTO_MEDICAMENTO1`
    FOREIGN KEY (`MEDICAMENTO_ID`)
    REFERENCES `MEDICAMENTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

INSERT INTO APLICACAO_MEDICAMENTO VALUES (1,"28-07-2015",200,"ANIMAL ESTAVA FRACO E NÃO CAMINHAVA DIREITO",1,1);